services:
  fastapi:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST="0.0.0.0"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"