services:
  web:
    build: ./src/st_web
    ports:
      - 8501:8501
    depends_on:
      - backend
    networks:
      - mynet

  backend:
    build: ./src/backend
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - mynet

  db:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
    networks:
      - mynet

networks:
  mynet:
    driver: bridge